SysHotelv1/Models/BookingStatus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SysHotelv1.Models
{
    public partial class BookingStatus
    {
        public int Id { get; set; }
        public string DescriptionStatus { get; set; }
        public ICollection<Reservation> Reservations { get; set; }
    }
}

SysHotelv1/Controllers/BookingStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SysHotelv1.Models;

namespace SysHotelv1.Controllers
{
    [Authorize]

    public class BookingStatusController : BaseController
    {
        private SysHotelDataContext db = new SysHotelDataContext();

        // GET: BookingStatus
        public ActionResult Index()
        {
            return View(db.BookingStatuses.ToList());
        }

        // GET: BookingStatus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingStatus bookingStatus = db.BookingStatuses.Find(id);
            if (bookingStatus == null)
            {
                return HttpNotFound();
            }
            return View(bookingStatus);
        }

        // GET: BookingStatus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookingStatus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DescriptionStatus")] BookingStatus bookingStatus)
        {
            if (ModelState.IsValid)
            {
                db.BookingStatuses.Add(bookingStatus);
                db.SaveChanges();
                Alert("Guardado con exito", Utilities.NotificationType.warning);
            }

            return View(bookingStatus);
        }

        // GET: BookingStatus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingStatus bookingStatus = db.BookingStatuses.Find(id);
            if (bookingStatus == null)
            {
                return HttpNotFound();
            }
            return View(bookingStatus);
        }

        // POST: BookingStatus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DescriptionStatus")] BookingStatus bookingStatus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookingStatus).State = EntityState.Modified;
                db.SaveChanges();
                Alert("Guardado con exito", Utilities.NotificationType.warning);
            }
            return View(bookingStatus);
        }

        // GET: BookingStatus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingStatus bookingStatus = db.BookingStatuses.Find(id);
            if (bookingStatus == null)
            {
                return HttpNotFound();
            }
            return View(bookingStatus);
        }

        // POST: BookingStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BookingStatus bookingStatus = db.BookingStatuses.Find(id);
            db.BookingStatuses.Remove(bookingStatus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SysHotelv1/Views/BookingStatus/Create.cshtml
@model SysHotelv1.Models.BookingStatus

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Estatus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescriptionStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index","BookingStatus",htmlAttributes:new {@class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SysHotelv1/Views/BookingStatus/Delete.cshtml
@model SysHotelv1.Models.BookingStatus

@{
    ViewBag.Title = "Eliminar";
}

    <h2>Estatus </h2>>

<h3>Estas seguro que deseas eliminar este elemento?</h3>

<div>
    <h4>Estatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DescriptionStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionStatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Volver a la Lista", "Index","BookingStatus", htmlAttributes: new {@class="btn btn-primary"})
        </div>
    }
</div>

SysHotelv1/Views/BookingStatus/Details.cshtml
@model SysHotelv1.Models.BookingStatus

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BookingStatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DescriptionStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionStatus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SysHotelv1/Views/BookingStatus/Edit.cshtml
@model SysHotelv1.Models.BookingStatus

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Estatus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescriptionStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriptionStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Cambios" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index","BookingStatus", htmlAttributes: new {@class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SysHotelv1/Views/BookingStatus/Index.cshtml
@model IEnumerable<SysHotelv1.Models.BookingStatus>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear nuevo", "Create", "BookingStatus", htmlAttributes: new {@class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DescriptionStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DescriptionStatus)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }, htmlAttributes: new {@class = "btn btn-primary" }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }, htmlAttributes: new {@class = "btn btn-danger" })
        </td>
    </tr>
}

</table>