SysHotelv1/Models/Invoices.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SysHotelv1.Models
{
    public partial class Invoices
    {
        public int Id { get; set; }
        public int ReservationDetailsId { get; set; }
        public ReservationDetails ReservationDetails { get; set; }
        public decimal PriceAdult { get; set; }
        public decimal PriceChild { get; set; }
        public int DayCount { get; set; }
        public decimal SeasonalDiscount { get; set; }
        public int Total { get; set; }

    }
}

SysHotelv1/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SysHotelv1.Models;

namespace SysHotelv1.Controllers
{
    [Authorize]

    public class InvoicesController : Controller
    {
        private SysHotelDataContext db = new SysHotelDataContext();

        // GET: Invoices
        public ActionResult Index()
        {
            var invoices = db.Invoices.Include(i => i.ReservationDetails);
            return View(invoices.ToList());
        }

        // GET: Invoices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = db.Invoices.Find(id);
            if (invoices == null)
            {
                return HttpNotFound();
            }
            return View(invoices);
        }

        // GET: Invoices/Create
        public ActionResult Create()
        {
            ViewBag.ReservationDetailsId = new SelectList(db.ReservationDetails, "Id", "Id");
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ReservationDetailsId,PriceAdult,PriceChild,DayCount,SeasonalDiscount,Total")] Invoices invoices)
        {
            if (ModelState.IsValid)
            {
                db.Invoices.Add(invoices);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ReservationDetailsId = new SelectList(db.ReservationDetails, "Id", "Id", invoices.ReservationDetailsId);
            return View(invoices);
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = db.Invoices.Find(id);
            if (invoices == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReservationDetailsId = new SelectList(db.ReservationDetails, "Id", "Id", invoices.ReservationDetailsId);
            return View(invoices);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ReservationDetailsId,PriceAdult,PriceChild,DayCount,SeasonalDiscount,Total")] Invoices invoices)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoices).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ReservationDetailsId = new SelectList(db.ReservationDetails, "Id", "Id", invoices.ReservationDetailsId);
            return View(invoices);
        }

        // GET: Invoices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = db.Invoices.Find(id);
            if (invoices == null)
            {
                return HttpNotFound();
            }
            return View(invoices);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoices invoices = db.Invoices.Find(id);
            db.Invoices.Remove(invoices);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SysHotelv1/Views/Invoices/Create.cshtml
@model SysHotelv1.Models.Invoices

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoices</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ReservationDetailsId, "ReservationDetailsId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ReservationDetailsId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ReservationDetailsId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceAdult, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceAdult, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceAdult, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceChild, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceChild, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceChild, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DayCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DayCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SeasonalDiscount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeasonalDiscount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeasonalDiscount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Volver a la Lista", "Index", "Invoices", htmlAttributes: new { @class = "btn btn-primary" })
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SysHotelv1/Views/Invoices/Delete.cshtml
@model SysHotelv1.Models.Invoices

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Estas seguro que deseas eliminar este elemento?</h3>

<div>
    <h4>Invoices</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDetails.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDetails.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceAdult)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceAdult)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceChild)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceChild)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DayCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SeasonalDiscount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SeasonalDiscount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Volver a la Lista", "Index", "Invoices", htmlAttributes: new { @class = "btn btn-primary" })

    </div>
    }
</div>

SysHotelv1/Views/Invoices/Details.cshtml
@model SysHotelv1.Models.Invoices

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Invoices</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDetails.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDetails.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceAdult)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceAdult)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceChild)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceChild)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DayCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SeasonalDiscount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SeasonalDiscount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SysHotelv1/Views/Invoices/Edit.cshtml
@model SysHotelv1.Models.Invoices

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoices</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ReservationDetailsId, "ReservationDetailsId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ReservationDetailsId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ReservationDetailsId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceAdult, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceAdult, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceAdult, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceChild, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceChild, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceChild, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DayCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DayCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SeasonalDiscount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeasonalDiscount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeasonalDiscount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Cambios" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Volver a la Lista", "Index", "Invoices", htmlAttributes: new { @class = "btn btn-primary" })
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SysHotelv1/Views/Invoices/Index.cshtml
@model IEnumerable<SysHotelv1.Models.Invoices>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ReservationDetails.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PriceAdult)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PriceChild)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DayCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeasonalDiscount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ReservationDetails.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PriceAdult)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PriceChild)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DayCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SeasonalDiscount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>